import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'

// Flat ESLint configuration for the Vite/React app. It combines the base JS
// recommended rules with React Hooks and React Refresh checks, then applies them
// only to JavaScript/JSX source files. The production build output is ignored so
// generated files do not create lint noise.
export default defineConfig([
  // dist is generated by Vite and should be validated through the build step,
  // not linted as source.
  globalIgnores(['dist']),
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      // Browser globals allow direct use of window, document, localStorage, and
      // other DOM APIs throughout App.jsx without declaring them manually.
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    rules: {
      // Vite/React patterns often keep PascalCase components or constants that
      // are referenced dynamically. This rule still catches real unused values
      // while avoiding false positives for upper-case exported-style names.
      'no-unused-vars': ['error', { varsIgnorePattern: '^(motion|[A-Z_])' }],
    },
  },
])
